### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [jessejameswoods/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/jessejameswoods/prj-rev-bwfs-dasmoto/blob/0ea41c4424a7026ebd6bbc9330fbfb396de9d25c/Dasmoto's%20Arts%20%26%20Crafts/index.html#L5

**Comment by jessejameswoods** [comment]
good point thanks.
