### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by martoio** [jessejameswoods/prj-rev-bwfs-dasmoto#2]
Good job on separating the HTML into sections! One thing you might want to consider is changing the ``<div>`` into a ``<section>`` to improve the semantics of your code.
If you aren't familiar with semantic HTML: http://www.hongkiat.com/blog/html-5-semantics/
Example:
```
<!-- First section -->
<section> <!-- or <div>, but <section> is more semantic -->
 <h2 class="brushes">Brushes</h2>
 <img src="#" alt="#" />
 <h3>Text</h3>
 <p>
  Lorem <span class="price">ipsum</span>
 </p>
</section>
```
https://github.com/jessejameswoods/prj-rev-bwfs-dasmoto/blob/0ea41c4424a7026ebd6bbc9330fbfb396de9d25c/Dasmoto's%20Arts%20%26%20Crafts/index.html#L16-L23

**Comment by jessejameswoods** [comment]
thank you for your feedback and the suggestion for improving the semantics.
